language: python

cache:
  directories:
  - blender

python:
  - "3.5"

before_install:
 # install blender and dependencies
  - sudo apt-get update -qq
  - sudo apt-get install blender

install:
  # check if a blender installation has been previously cached
  - sh ./ci_install_blender.sh
  - sudo ln -s ${PWD}/src/io_scene_ogex ${PWD}/blender/2.77/scripts/addons/io_scene_ogex

script: ./blender/blender --background --python-exit-code 1 --python run_tests.py
