language: python

python:
  - "3.5"

before_install:
 # install blender and dependencies
  - sudo apt-get update -qq
  - sudo apt-get install blender

install:
  # create temp directory where we store a recent blender version
  - mkdir tmp && cd tmp && mkdir blender

  # download the blender version you want to test against
  - wget http://download.blender.org/release/Blender2.77/blender-2.77-linux-glibc211-x86_64.tar.bz2
  # Extract the archive
  - tar jxf blender-2.77-linux-glibc211-x86_64.tar.bz2 -C blender --strip-components 1

  - cd ..

  - sudo ln -s ${PWD}/src/io_scene_ogex ${PWD}/tmp/blender/2.77/scripts/addons/io_scene_ogex

script: ./tmp/blender/blender --background --python-exit-code 1 --python run_tests.py
